export enum OrderStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACCEPT = 'ACCEPT',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  PACKING = 'PACKING',
  AWAITING_PAYMENT_VERIFICATION = 'AWAITING_PAYMENT_VERIFICATION',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  ORDERED_FROM_SUPPLIER = 'ORDERED_FROM_SUPPLIER',
  READY_FOR_BILLING = 'READY_FOR_BILLING',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  PAID = 'PAID',
}
