import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/styles/globals.css";
import { AuthProvider } from "@/features/auth/hooks/useAuth";
import { getSession } from "@/lib/session";
import { Toaster } from 'sonner';

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Omega houseware",
  description: "Generated by create next app",
  icons: {
    icon: "/omega_favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Toaster 
          theme="light"
          position="top-right"
          richColors
        />
      </body>
    </html>
  );
}
